/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package ai.ilikeplaces.entities;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Subscriber extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Subscriber\",\"namespace\":\"ai.ilikeplaces.entities\",\"fields\":[{\"name\":\"emailId\",\"type\":\"string\"}]}");
  @Deprecated public java.lang.CharSequence emailId;

  /**
   * Default constructor.
   */
  public Subscriber() {}

  /**
   * All-args constructor.
   */
  public Subscriber(java.lang.CharSequence emailId) {
    this.emailId = emailId;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return emailId;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: emailId = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'emailId' field.
   */
  public java.lang.CharSequence getEmailId() {
    return emailId;
  }

  /**
   * Sets the value of the 'emailId' field.
   * @param value the value to set.
   */
  public void setEmailId(java.lang.CharSequence value) {
    this.emailId = value;
  }

  /** Creates a new Subscriber RecordBuilder */
  public static ai.ilikeplaces.entities.Subscriber.Builder newBuilder() {
    return new ai.ilikeplaces.entities.Subscriber.Builder();
  }
  
  /** Creates a new Subscriber RecordBuilder by copying an existing Builder */
  public static ai.ilikeplaces.entities.Subscriber.Builder newBuilder(ai.ilikeplaces.entities.Subscriber.Builder other) {
    return new ai.ilikeplaces.entities.Subscriber.Builder(other);
  }
  
  /** Creates a new Subscriber RecordBuilder by copying an existing Subscriber instance */
  public static ai.ilikeplaces.entities.Subscriber.Builder newBuilder(ai.ilikeplaces.entities.Subscriber other) {
    return new ai.ilikeplaces.entities.Subscriber.Builder(other);
  }
  
  /**
   * RecordBuilder for Subscriber instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Subscriber>
    implements org.apache.avro.data.RecordBuilder<Subscriber> {

    private java.lang.CharSequence emailId;

    /** Creates a new Builder */
    private Builder() {
      super(ai.ilikeplaces.entities.Subscriber.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(ai.ilikeplaces.entities.Subscriber.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing Subscriber instance */
    private Builder(ai.ilikeplaces.entities.Subscriber other) {
            super(ai.ilikeplaces.entities.Subscriber.SCHEMA$);
      if (isValidValue(fields()[0], other.emailId)) {
        this.emailId = data().deepCopy(fields()[0].schema(), other.emailId);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'emailId' field */
    public java.lang.CharSequence getEmailId() {
      return emailId;
    }
    
    /** Sets the value of the 'emailId' field */
    public ai.ilikeplaces.entities.Subscriber.Builder setEmailId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.emailId = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'emailId' field has been set */
    public boolean hasEmailId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'emailId' field */
    public ai.ilikeplaces.entities.Subscriber.Builder clearEmailId() {
      emailId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public Subscriber build() {
      try {
        Subscriber record = new Subscriber();
        record.emailId = fieldSetFlags()[0] ? this.emailId : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
